name: bPermissions
version: 1.2
author: codename_B
website: http://tetragaming.com/codename_B/
main: de.bananaco.permissions.Permissions
commands:
  permissions:
    description: reloads the nodes
    usage: |
      /<command> help for usage
  p:
    description: reloads the nodes
    usage: |
      /<command> help for usage