name: bPermissions
version: 1.0
author: codename_B
website: http://tetragaming.com/codename_B/
main: com.ubempire.permissions.Permissions
commands:
  nodereload:
    description: reloads the nodes
    usage: |
      /<command>
  setgroup:
    description: sets the group of a player in a particular world
    usage: |
      /<command> player group world
  addnode:
    description: add a node to a group
    usage: |
      /<command> node group world
  rmnode:
    description: removes a node from a group
    usage: |
      /<command> node group world
  lsnode:
    description: lists the nodes of a group
    usage: |
      /<command> group world